modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/FrostedHeart/issues"
[[mods]] #mandatory
modId = "frostedheart" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "TWR Frosted Heart" #mandatory
authors = "Developed by TeamMoegMC, with the help of many contributors. See description below."
description = '''
The Core Mod for The Winter Rescue Modpack.

 (In the order of first joining, not contribution size)

Development Team:
- Technical: YueSha, duck_egg, dashuaibia, khjxiaogu, yuqijun
- Art: Lyuuke, gomou_g, Fu_Yang, OEIIO(03110), Dsanilin
- Design: alphaGem, Jacky_Wang
- QA: asdfghjkl, shidi
- Operation: Evan

Contributors:
LetterN, collin-marando, sayyidyofa, Whitealbum0, alyashour, AGmouse, Jerzerak,
nekocrane, Huaji_Qinmi, Heitao, ceary741, Gugusb, Winged-Hussars,
IBlessus, GuardianWorld(Mixxs), Keisari, ewoudjie, ZXCZST, Lanshan
'''
[[dependencies.frostedheart]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"
