modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/FrostedHeart/issues"
[[mods]] #mandatory
modId = "frostedheart" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "TWR Frosted Heart" #mandatory
authors = "[TeamMoeg] YueSha, dashuaibia, khjxiaogu, duck_egg, Lyuuke, gomou_g"
description = '''
Some heat in the cold...
'''
[[dependencies.frostedheart]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.16.5-5.0.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="primalwinter"
    mandatory=true
    versionRange="[1.16.4-2.0.5,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="watersource"
    mandatory=true
    versionRange="[1.1.33-beta-1.16.5,)"
    ordering="BEFORE"
    side="BOTH"
    
[[dependencies.frostedheart]]
    modId="thermopolium"
    mandatory=true
    versionRange="[0.2.12,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="create"
    mandatory=true
    versionRange="[v0.3.2d,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.16-0.2.3,1.16-0.3)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="rankine"
    mandatory=true
    versionRange="[1.2,1.4)"
    ordering="AFTER"
    side="BOTH"
